export default{
    products:[
        {
            _id:'1',
            name:'Full Zip running shirt',
            category:'Shirt',
            image:'/images/product-1.jpg',
            price:100,
            brand:'Hiskywin',
            rating:4.4,
            numReviews:10,
            countInStock:6
        },
        {
            _id:'2',
            name:'T-Shirt',
            category:'Shirt',
            image:'/images/product-2.jpg',
            price:120,
            brand:'Hiskywin',
            rating:4.5,
            numReviews:10,
            countInStock:6
        },
        {
            _id:'3',
            name:'T-Shirt',
            category:'Shirt',
            image:'/images/product-3.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            countInStock:3
        },
        {
            _id:'4',
            name:'Long-Shirt',
            category:'Shirt',
            image:'/images/product-1.jpg',
            price:120,
            brand:'Adidas',
            rating:4.5,
            numReviews:10,
            countInStock:6
        },
    ]
}